### DISCUSSION TITLE
Different children type in section

### DISCUSSION THREAD

**Discussion by steveb05** [SpongePowered/Configurate#303] [Support] [answered]
I have a similar situation, where I want to allow the end user to specify a list of entities, in the config I have global values specified at the beginning, and optionally values that are per-mob. My solution is this following:

```yaml
mob-modifier:
  percentage-drop: 50.0
  range-drop: 10-30
  mob-list:
    - PIG
    - ZOMBIE:
        percentage-drop: 50.0
        range-drop: 10-30
```

Except I have the following problem. When I want to iterate for all values, I usually use ```childrenMap()``` or ```childrenList()```, something like this: 
```java
for (final Object entityTypeKey : mobListNode.childrenMap().keySet()) {
  final EntityType entityType = EntityType.valueOf(mobListNode.node(entityTypeKey));
}
``` 
problem that in this case there are both types, and I don't know how to get the values, any idea how to do that?
