### DISCUSSION TITLE
Bug with key words?

### DISCUSSION THREAD

**Discussion by BrainRTP** [SpongePowered/Configurate#329] [Support] [answered]
Hi! I have this `language.yaml`
```yaml

command:
  setSpawnpoint: "spawnpoint"
  teleport: "telepor"
  toggleMsg:
    on: "message enable"
    off: "message disable"
```
When i try get `command.toggleMsg.on` or `command.toggleMsg.off` i have null (in this case `Missing language key - [command, toggleMsg, off]`).
Code
```java
configuration.get().node("command", "toggleMsg", "off").getString("&cMissing language key - &e" + Arrays.toString(key))
```

It is bug or not?
