### DISCUSSION TITLE
Having knowledges about missing/unexpected properties in a config file at deserialization time

### DISCUSSION THREAD

**Discussion by Djaytan** [SpongePowered/Configurate#374] [Support] [answered]
Hello,

After some searches I didn't find my answer.

Let's take directly an example. I have the following simple config file with a valid content:
```yaml
hostname: "example.com"
port: 1234
isSslEnabled: true
```

But I want that any unexpected properties must lead to a failure like this is the case for the following content:
```yaml
hostname: "example.com"
port: 1234
isSslEnabled: true
unexpectedField: test
```

To fail on missing fields, I know it exists the method `ConfigurationNode#require` but which seems usable only when creating a custom `TypeSerializer`.

What about when having a class annotated with `@ConfigSerializable` like for the following simplified one:
```java
@ConfigSerializable
// Lombok annotations...
public final class HostValidatingProperties
    extends ValidatingConvertibleProperties<HostProperties> {

  private String hostname;
  private int port;
  private boolean isSslEnabled;

  // Other methods...
}
```

Is there a way to configure the `ObjectMapper`/`TypeSerializer` to reach the wanted behavior? Even having just a way to detect that a `ConfigurationNode` has unexpected/missing fields would be enough without speaking about failing / sending warning logs or whatever else.

Even if we can find solutions for missing fields, this isn't the same story for unexpected ones.
