### ISSUE TITLE
YAML format gets refactored when saving.

### ISSUE THREAD

**Issue by Runkang10** [SpongePowered/Configurate#557]
Before calling the save function:
```YAML
- uuid: a9b45d2a-b9ce-3d96-a27f-3b68ba9ec158
  durationType: TEMP
  duration: '2025-04-01T10:15:30Z'
```

After calling it:
```YAML
- {uuid: a9b45d2a-b9ce-3d96-a27f-3b68ba9ec158, durationType: TEMP, duration: '2025-04-01T10:15:30Z'}
```
